### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Dragosha** [AGulev/DefUnityAds#1]
default	22:27:03.998332 +0500	DefUnityAds	INFO:DLIB: Log server started on port 49367
default	22:27:03.998776 +0500	DefUnityAds	INFO:ENGINE: Engine service started on port 8001
default	22:27:03.998819 +0500	DefUnityAds	INFO:ENGINE: Defold Engine 1.2.127 (c129eaf)
default	22:27:04.018835 +0500	DefUnityAds	Retrieving resting unlock: 0
default	22:27:04.718933 +0500	DefUnityAds	INFO:ENGINE: Loading data from: dmanif:/var/containers/Bundle/Application/AAE9998D-F3CD-484A-A2B6-66488BB03FD0/DefUnityAds.app/game.dmanifest
default	22:27:04.743339 +0500	DefUnityAds	[CLIoHidInterface] Adding new Device with usage pair {65280, 3}
default	22:27:04.745245 +0500	DefUnityAds	[CLIoHidInterface] invalidating hid service refs
default	22:27:04.745702 +0500	DefUnityAds	[CLIoHidInterface] Refreshing service refs
default	22:27:04.745801 +0500	DefUnityAds	Requesting calls from host
default	22:27:04.746156 +0500	DefUnityAds	Received requested calls from host: <private>
default	22:27:04.754778 +0500	DefUnityAds	[CLIoHidInterface] Event system client initialized successfully
default	22:27:04.755359 +0500	DefUnityAds	[CLIoHidInterface] invalidating hid service refs
default	22:27:04.755596 +0500	DefUnityAds	[CLIoHidInterface] Refreshing service refs
default	22:27:05.078906 +0500	DefUnityAds	1366: Starting AURemoteIO(0x10e83bc40)
output client:  2 ch,  44100 Hz, Float32, non-inter, output HW:  2 ch,  44100 Hz, Float32, non-inter
input client:   2 ch,      0 Hz, Float32, non-inter, input HW:   2 ch,      0 Hz, Float32, non-inter
default	22:27:05.079701 +0500	DefUnityAds	1376: work interval port 0x7e03
default	22:27:05.294531 +0500	DefUnityAds	INFO:ENGINE: Initialised sound device 'default'
default	22:27:05.308789 +0500	DefUnityAds	DEBUG:SCRIPT: VERSION IS: 	2.2.1
default	22:27:05.309690 +0500	DefUnityAds	DEBUG:SCRIPT: DEBUG MODE IS:	false
default	22:27:05.315131 +0500	DefUnityAds	DEBUG:SCRIPT: isInitialized:	false
default	22:27:05.315417 +0500	DefUnityAds	DEBUG:SCRIPT: isSupported:	true
default	22:27:05.316423 +0500	DefUnityAds	INFO:CRASH: Successfully wrote Crashdump to file: /var/mobile/Containers/Data/Application/6FA658B3-33C6-4E8D-ACBE-472BDF1A7410/Library/Application Support/Defold/_crash

[DefUnityAds-2018-05-11-222707.crash.txt](https://github.com/AGulev/DefUnityAds/files/1996375/DefUnityAds-2018-05-11-222707.crash.txt)

**Comment by AGulev** [comment]
fixed here https://github.com/AGulev/DefUnityAds/releases/tag/1.1.0
thanks for the report.
