### ISSUE TITLE
Allow NSUserTrackingUsageDescription to be configurable

### ISSUE THREAD

**Issue by totebo** [AGulev/DefUnityAds#18]
If more than one extension uses the NSUserTrackingUsageDescription the description might be overwritten by DefVideoAds hard coded one.

Forum thread: https://forum.defold.com/t/advertising-info-extension-message/67923/3

**Comment by AGulev** [comment]
I'll take a look. What do you think is a good solution here? Provide it as optional field in game.project?

**Comment by totebo** [comment]
Thanks! Yeah, this is how Ad Info does it:

[adinfo]
tracking_usage_description = Want to help us make Swiing a better game? Allow us to track your activity in-game for our performance analytics and providing relevant ads!

At least then I can make sure the two messages are identical, even if they become repeated in the Info.plist.

**Comment by AGulev** [comment]
Solved in https://github.com/AGulev/DefVideoAds/releases/tag/3.5.3
