### ISSUE TITLE
Android: Banner ads cutout in phone safe area

### ISSUE THREAD

**Issue by kornyushin** [AGulev/DefUnityAds#24]
Run example on android phone, show banner. if banner position in phone safe area, then part of banner cut out

![photo_2022-01-02_11-56-42](https://user-images.githubusercontent.com/1443375/147871107-3318da3c-7c04-4413-b3dc-a759bd7a8f66.jpg)
![photo_2022-01-02_11-56-48](https://user-images.githubusercontent.com/1443375/147871109-db27ed35-cd50-4362-93aa-9ba7830066a3.jpg)

**Comment by AGulev** [comment]
@kornyushin I can't repo this bug on my phones. But I tried a fix, could you pls check if this branch https://github.com/AGulev/DefVideoAds/archive/refs/heads/issue-24.zip has the same issue (or at least different in a some way)

**Comment by AGulev** [comment]
Now I can reproduce it on Huawei P20 Pro, Android 10. 
Oki, let me try a couple of tricks to fix that

**Comment by AGulev** [comment]
https://github.com/googleads/googleads-mobile-unity/issues/902
