### ISSUE TITLE
Redundant define for DLIB_LOG_DOMAIN

### ISSUE THREAD

**Issue by JCash** [AGulev/DefUnityAds#27]
(minor issue, but a bit noisy)

Each extension automatically get their own log domain set when building on the extender server.

```
WARNING: defunityads/src/unityads.cpp(5): 'DLIB_LOG_DOMAIN' macro redefined [-Wmacro-redefined]
#define DLIB_LOG_DOMAIN LIB_NAME
```

**Comment by AGulev** [comment]
fixed https://github.com/AGulev/DefVideoAds/commit/eca5fadeec7f98b37a5e0ec3a404e761fee79bac
