### ISSUE TITLE
[4.2.1] Crash after rewarded video on Android

### ISSUE THREAD

**Issue by SkaterDad** [AGulev/DefUnityAds#28]
Defold 1.3.6
DefVideoAds: 4.2.1

Device:  Google Pixel 6a
OS: Android 13 with Sept 5 Security Update and Aug 1 Google Play System Update.

What happens?
On game startup, I initialize Unity Ads and start fetching a rewarded video ad.

When the ad is loaded, I click a button to launch it.  After the 30 seconds timer on the ad, I click to close it.   The game crashes and I go back to the phone's home screen.

ADB log in details below:
<details>

09-22 22:55:04.599  1179  3428 I ActivityManager: Process dev.skaterdad.applespider (pid 11548) has died: fg  TOP
09-22 22:55:04.599  1179  3311 I WindowManager: WIN DEATH: Window{3a87836 u0 dev.skaterdad.applespider/com.dynamo.android.DefoldActivity}
09-22 22:55:04.599  1179  3311 W InputManager-JNI: Input channel object '3a87836 dev.skaterdad.applespider/com.dynamo.android.DefoldActivity (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.599  1179  2603 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10259/11548, [NetworkRequest [ LISTEN id=981, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND&NOT_VCN_MANAGED Uid: 10259 RequestorUid: 10259 RequestorPkg: dev.skaterdad.applespider UnderlyingNetworks: Null] ]], android.os.BinderProxy@ec76d58)
09-22 22:55:04.600  1179  5343 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10259/11548, [NetworkRequest [ REQUEST id=980, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10259 RequestorUid: 10259 RequestorPkg: dev.skaterdad.applespider UnderlyingNetworks: Null] ]], android.os.BinderProxy@84a8eb1)
09-22 22:55:04.600  1179  2603 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10259/11548, [NetworkRequest [ LISTEN id=982, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND&NOT_VCN_MANAGED Uid: 10259 RequestorUid: 10259 RequestorPkg: dev.skaterdad.applespider UnderlyingNetworks: Null] ]], android.os.BinderProxy@d1edf96)
09-22 22:55:04.600   794   794 I Zygote  : Process 11548 exited due to signal 11 (Segmentation fault)
09-22 22:55:04.601  1179  1913 D ConnectivityService: releasing NetworkRequest [ REQUEST id=980, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10259 RequestorUid: 10259 RequestorPkg: dev.skaterdad.applespider UnderlyingNetworks: Null] ] (release request)
09-22 22:55:04.603  1179  2603 I WindowManager: WIN DEATH: Window{a728d3d u0 dev.skaterdad.applespider/com.unity3d.services.ads.adunit.AdUnitActivity}
09-22 22:55:04.603  1179  2603 W InputManager-JNI: Input channel object 'a728d3d dev.skaterdad.applespider/com.unity3d.services.ads.adunit.AdUnitActivity (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.603   654   654 W libprocessgroup: Failed to apply NoResetUclampGrp task profile: No such process
09-22 22:55:04.603   654   654 W powerhal-libperfmgr: Failed to set NoResetUclampGrp task profile for tid:11736
09-22 22:55:04.603   654   654 W libprocessgroup: Failed to apply NoResetUclampGrp task profile: No such process
09-22 22:55:04.603   654   654 W powerhal-libperfmgr: Failed to set NoResetUclampGrp task profile for tid:11737
09-22 22:55:04.603   654   654 W libprocessgroup: Failed to apply NoResetUclampGrp task profile: No such process
09-22 22:55:04.603   654   654 W powerhal-libperfmgr: Failed to set NoResetUclampGrp task profile for tid:11548
09-22 22:55:04.603   654   654 W libprocessgroup: Failed to apply NoResetUclampGrp task profile: No such process
09-22 22:55:04.603   654   654 W powerhal-libperfmgr: Failed to set NoResetUclampGrp task profile for tid:11566
09-22 22:55:04.603   654   654 W powerhal-libperfmgr: sched_setattr failed for thread 11736, err=3
09-22 22:55:04.603   654   654 W powerhal-libperfmgr: sched_setattr failed for thread 11737, err=3
09-22 22:55:04.603   654   654 W powerhal-libperfmgr: sched_setattr failed for thread 11548, err=3
09-22 22:55:04.603   654   654 W powerhal-libperfmgr: sched_setattr failed for thread 11566, err=3
09-22 22:55:04.607  1179  3428 W InputManager-JNI: Input channel object 'Letterbox_left_ActivityRecord{a8418da u0 dev.skaterdad.applespider/com.unity3d.services.ads.adunit.AdUnitActivity} t3416} (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.608  1179  3428 W InputManager-JNI: Input channel object 'Letterbox_top_ActivityRecord{a8418da u0 dev.skaterdad.applespider/com.unity3d.services.ads.adunit.AdUnitActivity} t3416} (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.608  1179  3428 W InputManager-JNI: Input channel object 'Letterbox_right_ActivityRecord{a8418da u0 dev.skaterdad.applespider/com.unity3d.services.ads.adunit.AdUnitActivity} t3416} (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.608  1179  3428 W InputManager-JNI: Input channel object 'Letterbox_bottom_ActivityRecord{a8418da u0 dev.skaterdad.applespider/com.unity3d.services.ads.adunit.AdUnitActivity} t3416} (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.608  1179  3428 W ActivityTaskManager: Force removing ActivityRecord{a620f81 u0 dev.skaterdad.applespider/com.dynamo.android.DefoldActivity} t3416}: app died, no saved state
09-22 22:55:04.609  1179  3428 W InputManager-JNI: Input channel object 'Letterbox_left_ActivityRecord{a620f81 u0 dev.skaterdad.applespider/com.dynamo.android.DefoldActivity} t3416} (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.609  1179  1629 I libprocessgroup: Successfully killed process cgroup uid 10259 pid 11548 in 0ms
09-22 22:55:04.609  1179  3428 W InputManager-JNI: Input channel object 'Letterbox_top_ActivityRecord{a620f81 u0 dev.skaterdad.applespider/com.dynamo.android.DefoldActivity} t3416} (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.609  1179  3428 W InputManager-JNI: Input channel object 'Letterbox_right_ActivityRecord{a620f81 u0 dev.skaterdad.applespider/com.dynamo.android.DefoldActivity} t3416} (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.609  1179  3428 W InputManager-JNI: Input channel object 'Letterbox_bottom_ActivityRecord{a620f81 u0 dev.skaterdad.applespider/com.dynamo.android.DefoldActivity} t3416} (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.613   516   516 E BpTransactionCompletedListener: Failed to transact (-32)
09-22 22:55:04.625  3389  4424 I AssistantForeground: (REDACTED) Get launcher package: %s
09-22 22:55:04.627  1179  1566 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
09-22 22:55:04.627 29832 29832 I A       : (REDACTED) onApplyWindowInsets: systemWindowInsets=%s
09-22 22:55:04.627 29832 29832 I A       : (REDACTED) onApplyWindowInsets: systemWindowInsets=%s
09-22 22:55:04.630  2930  2930 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.auth.api.signin.service.START pkg=com.google.android.gms }
09-22 22:55:04.636  2434  2618 D QuickstepModelDelegate: notifyAppTargetEvent action=1 launchLocation=
09-22 22:55:04.639  1179  1568 W WindowManager: Failed to deliver inset state change to w=Window{3a87836 u0 dev.skaterdad.applespider/com.dynamo.android.DefoldActivity EXITING}
09-22 22:55:04.639  1179  1568 W WindowManager: android.os.DeadObjectException
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.os.BinderProxy.transactNative(Native Method)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.os.BinderProxy.transact(BinderProxy.java:584)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3994)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$5(InsetsStateController.java:348)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.wm.InsetsStateController.$r8$lambda$ni7v3ZO6TRbLZqXOFahDjPeXTS0(Unknown Source:0)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda4.run(Unknown Source:2)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:106)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.wm.WindowAnimator.$r8$lambda$fo2Nk5bb9hY3lvmHsTnTEwtZMbI(Unknown Source:0)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(Unknown Source:2)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.view.Choreographer.doCallbacks(Choreographer.java:899)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.view.Choreographer.doFrame(Choreographer.java:827)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.os.Handler.handleCallback(Handler.java:942)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:99)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.os.Looper.loopOnce(Looper.java:201)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.os.Looper.loop(Looper.java:288)
09-22 22:55:04.639  1179  1568 W WindowManager:         at android.os.HandlerThread.run(HandlerThread.java:67)
09-22 22:55:04.639  1179  1568 W WindowManager:         at com.android.server.ServiceThread.run(ServiceThread.java:44)
09-22 22:55:04.643  1179  3428 W WindowManager: Failed looking up window session=Session{c347e2a 31168:u0a10140} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5893 com.android.server.wm.WindowManagerService.removeWindow:2031 com.android.server.wm.Session.remove:223
09-22 22:55:04.643  1179  3428 W InputManager-JNI: Input channel object 'Embedded{} (client)' was disposed without first being removed with the input manager!
09-22 22:55:04.643  3389  3389 I GsaVoiceInteractionSrv: Handling ACTION_START_HOTWORD
09-22 22:55:04.644  3389  4253 I GsaVoiceInteractionSrv: (REDACTED) disregardVoiceMatch: %b
09-22 22:55:04.648 31168 31168 I OverlaySession: onDestroy: OverlaySessionInfo{taskId=3416, gamePackageName=dev.skaterdad.applespider} [CONTEXT service_id=311 ]
09-22 22:55:04.648  3370  3738 I AiAiEcho: Predicting[1]: { Feature:1, creation:2022-09-23T03:34:46.752Z, expiry:2022-09-23T09:34:46.752Z, isExpired: false}
09-22 22:55:04.649  3370  3738 I AiAiEcho: Ranked targets strategy: WEIGHTED, count: 1, ranking metadata: { cardId: WEATHER-569377243, card type: 1, update time: 2022-09-23T03:34:46.752Z, expiration time: 2022-09-23T09:34:46.752Z, ranking metadata: RankingMetaData(urgency=0.856, priority=0.3, recency=1.0, rankScore=0.25680003, importantTimePoints=# mjw@7bca4) }
09-22 22:55:04.649  3370  3738 I AiAiEcho: #postPredictionTargets: Sending updates to UISurface lockscreen with targets# 1
09-22 22:55:04.650  3370  3738 I AiAiEcho: #postPredictionTargets: Sending updates to UISurface home with targets# 1
09-22 22:55:04.650  3370  3738 I AiAiEcho: #postPredictionTargets: Sending updates to UISurface media_data_manager with targets# 0
09-22 22:55:04.651  1979  1979 W BcSmartspaceCard: No title view to update
09-22 22:55:04.652  1979  1979 I BcSmartspaceCard: setFormattedContentDescription: textView=SUBTITLE, text=53°F, iconDescription=Clear, contentDescription=Clear, 53°F
09-22 22:55:04.664 29832 29832 I A       : (REDACTED) onApplyWindowInsets: systemWindowInsets=%s
09-22 22:55:04.664 29832 29832 I A       : (REDACTED) onApplyWindowInsets: systemWindowInsets=%s
09-22 22:55:04.669  3866  3866 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3274
09-22 22:55:04.670  3866  3866 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2166 repeatCheckTimes = 0, unlocked = true
09-22 22:55:04.670  3866  3866 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1957 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.google.android.apps.nexuslauncher fieldId=-1 fieldName=null extras=null}, false)
09-22 22:55:04.670  3866  3866 I GoogleInputMethodService: GoogleInputMethodService.shouldHideHeaderOnInitialState():4078 ShouldHideHeaderOnInitialState = false
09-22 22:55:04.670  3866  3866 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2166 repeatCheckTimes = 2, unlocked = true
09-22 22:55:04.672  1179  1568 W WindowManager: Failed to deliver inset state change to w=Window{3a87836 u0 dev.skaterdad.applespider/com.dynamo.android.DefoldActivity EXITING}
09-22 22:55:04.672  1179  1568 W WindowManager: android.os.DeadObjectException
09-22 22:55:04.672  1179  1568 W WindowManager:         at android.os.BinderProxy.transactNative(Native Method)
09-22 22:55:04.672  1179  1568 W WindowManager:         at android.os.BinderProxy.transact(BinderProxy.java:584)
09-22 22:55:04.672  1179  1568 W WindowManager:         at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3994)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$5(InsetsStateController.java:348)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.InsetsStateController.$r8$lambda$ni7v3ZO6TRbLZqXOFahDjPeXTS0(Unknown Source:0)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda4.run(Unknown Source:2)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:840)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:784)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
09-22 22:55:04.672  1179  1568 W WindowManager:         at android.os.Handler.handleCallback(Handler.java:942)
09-22 22:55:04.672  1179  1568 W WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:99)
09-22 22:55:04.672  1179  1568 W WindowManager:         at android.os.Looper.loopOnce(Looper.java:201)
09-22 22:55:04.672  1179  1568 W WindowManager:         at android.os.Looper.loop(Looper.java:288)
09-22 22:55:04.672  1179  1568 W WindowManager:         at android.os.HandlerThread.run(HandlerThread.java:67)
09-22 22:55:04.672  1179  1568 W WindowManager:         at com.android.server.ServiceThread.run(ServiceThread.java:44)
09-22 22:55:04.848  1179  1568 W WindowManager: Exception thrown during dispatchAppVisibility Window{a728d3d u0 dev.skaterdad.applespider/com.unity3d.services.ads.adunit.AdUnitActivity EXITING}
09-22 22:55:04.848  1179  1568 W WindowManager: android.os.DeadObjectException
09-22 22:55:04.848  1179  1568 W WindowManager:         at android.os.BinderProxy.transactNative(Native Method)
09-22 22:55:04.848  1179  1568 W WindowManager:         at android.os.BinderProxy.transact(BinderProxy.java:584)
09-22 22:55:04.848  1179  1568 W WindowManager:         at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:536)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3489)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1199)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:398)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6564)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:7351)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.WindowContainer$$ExternalSyntheticLambda4.onAnimationFinished(Unknown Source:2)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0(SurfaceAnimator.java:133)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.SurfaceAnimator.$r8$lambda$lRxTVOJy8fX752UbrFno9INW9hE(Unknown Source:0)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.SurfaceAnimator$$ExternalSyntheticLambda1.run(Unknown Source:8)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.AnimatingActivityRegistry.endDeferringFinished(AnimatingActivityRegistry.java:104)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.AnimatingActivityRegistry.notifyAboutToFinish(AnimatingActivityRegistry.java:77)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.ActivityRecord.shouldDeferAnimationFinish(ActivityRecord.java:7169)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$1(SurfaceAnimator.java:141)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.SurfaceAnimator.$r8$lambda$4PiCdaEsT4mA6LQVhqpeM5EoU9c(Unknown Source:0)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.SurfaceAnimator$$ExternalSyntheticLambda0.onAnimationFinished(Unknown Source:4)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.LocalAnimationAdapter.lambda$startAnimation$0(LocalAnimationAdapter.java:67)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.LocalAnimationAdapter.$r8$lambda$gPDCFw0mQLltlXqA3mL6IUKCwLs(Unknown Source:0)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.wm.LocalAnimationAdapter$$ExternalSyntheticLambda0.run(Unknown Source:6)
09-22 22:55:04.848  1179  1568 W WindowManager:         at android.os.Handler.handleCallback(Handler.java:942)
09-22 22:55:04.848  1179  1568 W WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:99)
09-22 22:55:04.848  1179  1568 W WindowManager:         at android.os.Looper.loopOnce(Looper.java:201)
09-22 22:55:04.848  1179  1568 W WindowManager:         at android.os.Looper.loop(Looper.java:288)
09-22 22:55:04.848  1179  1568 W WindowManager:         at android.os.HandlerThread.run(HandlerThread.java:67)
09-22 22:55:04.848  1179  1568 W WindowManager:         at com.android.server.ServiceThread.run(ServiceThread.java:44)
09-22 22:55:04.853  1179  1566 W ActivityManager: setHasOverlayUi called on unknown pid: 11548

</details>

**Comment by AGulev** [comment]
The crash is related to https://github.com/defold/defold/issues/6956
and reproducible only on Android 13

**Comment by AGulev** [comment]
Can't reproduce using the latest android 13 https://developer.android.com/about/versions/13/get-qpr

**Comment by SkaterDad** [comment]
I just reproduced this with my Production release, which used to work fine and is on an older Defold and older DefVideoAds.

 Still going to try your demo project tonight, but thought this would be good info to share.

Horray for OS bugs!

**Comment by SkaterDad** [comment]
I re-produced this bug in the demo app.  This was 4.4.0.  Everything worked great, but then crashed after I closed the reward ad by clicking the (x).

Here's the logcat output from launching, initializing, loading, and showing the rewarded ad.

[bug.txt](https://github.com/AGulev/DefVideoAds/files/9637800/bug.txt)

**Comment by AGulev** [comment]
Again, it's not related to the extension version or Defold version.
It's related only to the Android OS version.

 It is possible to reproduce the issue even without any extensions.

If you open this page https://developer.android.com/about/versions/13/get-qpr , login into an account you use on your Pixel, and approve beta installation to your phone - your game will work just fine after update.
