### ISSUE TITLE
iOS Simulator Build Target

### ISSUE THREAD

**Issue by SkaterDad** [AGulev/DefUnityAds#31]
Is it possible for this extension to be compatible with the x86_64 iOS simulator target?

It throws build errors due to missing architectures in various files.

Certainly not a deal breaker if this is too difficult.  I need to get a physical device soon.

<img width="1489" alt="Screen Shot 2022-11-06 at 12 03 12 PM" src="https://user-images.githubusercontent.com/13255599/200187319-d6ffb6fe-66dc-4cc7-b1a8-4add0519e7d5.png">

**Comment by AGulev** [comment]
Support added in 4.5.1 (works only with Defold 1.4.0)

**Comment by SkaterDad** [comment]
Thanks for speedy release!  🥇
