### ISSUE TITLE
Conflict with Defold 1.2.155 updates

### ISSUE THREAD

**Issue by kibot914** [AGulev/DefUnityAds#4]
Hi @AGulev ,

Thanks for your effort for this library.
But I face a build error after updating my Defold version to 1.2.155. It is probably related to the change of moving facebook extension into an external library. Is there any advice from your side? Thanks.

<img width="1361" alt="Screenshot 2019-05-29 at 10 43 28 AM" src="https://user-images.githubusercontent.com/13725006/58525705-4b363c80-81ff-11e9-9f5a-4a127b4dd147.png">

**Comment by AGulev** [comment]
Hi @kibot914 , Thank you for the report, I'll check it today

**Comment by AGulev** [comment]
Works now
