### ISSUE TITLE
Receiving Multiple Callbacks on AdClose event .

### ISSUE THREAD

**Issue by MrZak-dev** [AGulev/DefUnityAds#9]
I have used the extension with  a simple initialization 

```lua

function unity_ads_callbacks(self, msg_type, message)
	if msg_type == unityads.TYPE_DID_FINISH then
		if message.state == unityads.FINISH_STATE_COMPLETED then
			print("completed")
			pprint(message)
		elseif message.state == unityads.FINISH_STATE_SKIPPED then
			print("skipped")
			pprint(message)
		end
	end
end

function init(self)
	unityads.initialize("3678415",unity_ads_callbacks,true)
end

```

Whenever i play the default ad with `unityads.show()` or `unityads.show(placementId)` and close it i receive multiple callbacks at the same time instead of only one 

e.g . Defold console
```java
{ --[[0xd2eba4c0]]
  placementId = "video",
  state = 2
}
DEBUG:SCRIPT: completed
DEBUG:SCRIPT: 
{ --[[0xd2eba550]]
  placementId = "video",
  state = 2
}
DEBUG:SCRIPT: completed
DEBUG:SCRIPT: 
{ --[[0xd2eba5c0]]
  placementId = "video",
  state = 2
}
DEBUG:SCRIPT: completed
DEBUG:SCRIPT: 
{ --[[0xd2eba630]]
  placementId = "video",
  state = 2
}
DEBUG:SCRIPT: completed
DEBUG:SCRIPT: 
{ --[[0xd2eba6a0]]
  placementId = "video",
  state = 2
}
DEBUG:SCRIPT: completed
DEBUG:SCRIPT: 
{ --[[0xd2eba710]]
  placementId = "video",
  state = 2
}
DEBUG:SCRIPT: completed
DEBUG:SCRIPT: 
{ --[[0xd2eba780]]
  placementId = "video",
  state = 2
}
```

**Comment by AGulev** [comment]
I'll take a look.
If it's something with my layer (between Defold and native plugin) I'll fix it, but it's possible this is native plugin issue. 
I let you know after the investigation.

**Comment by MrZak-dev** [comment]
i got through this by using a flag whenever the code in the callback function run one time i disable this flag so it won't run another time .
or we can disable the callback function by `unityads.setCallback(nil)` , and activate it whenever needed ?
but the issues that the extension will keep running unused tasks in the background ?

**Comment by AGulev** [comment]
Hi, I tested on ios and android and I can't reproduce this issue. Pls, let me know what device you use, os version, and te other information that might help me.

**Comment by MrZak-dev** [comment]
I am using a Xiaomi Redmi 4X , i have another Xiaomi Device i will test on it and let you know soon .

**Comment by AGulev** [comment]
I tested on Xiaomi Redmi Note 4
But again, I don't see any logic problems in the plugin itself. If you have a couple of calls of the same event, that means this is a problem of the original SDK, I think, I can't do something here.

**Comment by MrZak-dev** [comment]
Not a problem i found a walk through this as i said before you can close this issue .
